version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
        REDIS_PASSWORD: password
    # mounting config here allows us to change the config without rebuilding
    # or redeploying the application
    volumes:
    - "$PWD/config.json:/app/config.json"
  redis:
    image: "bitnami/redis:latest"
    environment:
        REDIS_PASSWORD: password
